In [ ]:
1. Write a Python Program to Add Two Matrices?

In [21]:
#Answer1:

import numpy as np
mat1 = np.random.randint(2,5,size=(3,3))
mat2 = np.random.randint(2,5,size=(3,3))
mat3 = np.add(mat1,mat2)
print(mat1)
print("+")
print(mat2)
print("=")
print(mat3)

[[3 2 3]
 [3 2 2]
 [4 4 3]]
+
[[2 2 3]
 [3 2 3]
 [4 4 4]]
=
[[5 4 6]
 [6 4 5]
 [8 8 7]]


In [ ]:
2. Write a Python Program to Multiply Two Matrices?

In [23]:
#Answer2:

import numpy as np
mat1 = np.random.randint(2,5,size=(3,3))
mat2 = np.random.randint(2,5,size=(3,3))
mat3 = np.dot(mat1,mat2)
print(mat1)
print("*")
print(mat2)
print("=")
print(mat3)

[[3 4 3]
 [4 4 2]
 [3 2 2]]
*
[[4 2 4]
 [2 3 3]
 [4 2 2]]
=
[[32 24 30]
 [32 24 32]
 [24 16 22]]


In [ ]:
3. Write a Python Program to Transpose a Matrix?

In [28]:
#Answer3:

import numpy as np
mat1 = np.random.randint(2,5,size=(3,4))
mat2 = mat1.transpose()
print("Matrix before transpose:")
print(mat1)
print("Matrix after transpose: ")
print(mat2)




Matrix before transpose:
[[3 2 3 4]
 [3 3 2 2]
 [3 2 2 3]]
Matrix after transpose: 
[[3 3 3]
 [2 3 2]
 [3 2 2]
 [4 2 3]]


In [ ]:
4. Write a Python Program to Sort Words in Alphabetic Order?

In [35]:
#Answer4:

list = ["orange", "olive", "apple", "banana", "apricote"]
sorted_list = sorted(list)
print(list)
print("After sorting the list: ",sorted_list)

['orange', 'olive', 'apple', 'banana', 'apricote']
After sorting the list:  ['apple', 'apricote', 'banana', 'olive', 'orange']


In [ ]:
5. Write a Python Program to Remove Punctuation From a String?

In [57]:
#Answer5:
import re
 
string1 = "Hi! My name is Shahin. Wow! its raining."
string2 = re.sub(r'[^\w\s]','',string1)
 
print('String with Punctuation: ', string1)
print('String without Punctuation: ', string2)

String with Punctuation:  Hi! My name is Shahin. Wow! its raining.
String without Punctuation:  Hi My name is Shahin Wow its raining
